# Generated by Django 4.0.5 on 2022-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
