# Generated by Django 4.0.5 on 2022-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(default='', max_length=50, verbose_name='Аббревиатура'),
        ),
    ]
