# Generated by Django 4.0.5 on 2022-07-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_category_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default='', max_length=50, verbose_name='Аббревиатура'),
        ),
    ]
