# Generated by Django 4.0.5 on 2022-08-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0006_alter_task_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('initiator', models.CharField(max_length=250, verbose_name='Инициатор')),
                ('performer', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Исполнитель')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершить')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
